//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClienteConsola.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListadoAlbumOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaAlbumOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaAlbumOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarCancionAlbumOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuitarCancionAlbumOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarBandasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaBandaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaBandaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarIntegranteBandaOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuitarIntegranteBandaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCancionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaCancionOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaCancionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarIntegranteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaIntegranteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaIntegranteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::ClienteConsola.Properties.Settings.Default.ClienteConsola_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListadoAlbumCompletedEventHandler ListadoAlbumCompleted;
        
        /// <remarks/>
        public event AltaAlbumCompletedEventHandler AltaAlbumCompleted;
        
        /// <remarks/>
        public event BajaAlbumCompletedEventHandler BajaAlbumCompleted;
        
        /// <remarks/>
        public event AgregarCancionAlbumCompletedEventHandler AgregarCancionAlbumCompleted;
        
        /// <remarks/>
        public event QuitarCancionAlbumCompletedEventHandler QuitarCancionAlbumCompleted;
        
        /// <remarks/>
        public event ListarBandasCompletedEventHandler ListarBandasCompleted;
        
        /// <remarks/>
        public event AltaBandaCompletedEventHandler AltaBandaCompleted;
        
        /// <remarks/>
        public event BajaBandaCompletedEventHandler BajaBandaCompleted;
        
        /// <remarks/>
        public event AgregarIntegranteBandaCompletedEventHandler AgregarIntegranteBandaCompleted;
        
        /// <remarks/>
        public event QuitarIntegranteBandaCompletedEventHandler QuitarIntegranteBandaCompleted;
        
        /// <remarks/>
        public event ListarCancionesCompletedEventHandler ListarCancionesCompleted;
        
        /// <remarks/>
        public event AltaCancionCompletedEventHandler AltaCancionCompleted;
        
        /// <remarks/>
        public event BajaCancionCompletedEventHandler BajaCancionCompleted;
        
        /// <remarks/>
        public event ListarIntegranteCompletedEventHandler ListarIntegranteCompleted;
        
        /// <remarks/>
        public event AltaIntegranteCompletedEventHandler AltaIntegranteCompleted;
        
        /// <remarks/>
        public event BajaIntegranteCompletedEventHandler BajaIntegranteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoAlbum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOAlbum[] ListadoAlbum() {
            object[] results = this.Invoke("ListadoAlbum", new object[0]);
            return ((VOAlbum[])(results[0]));
        }
        
        /// <remarks/>
        public void ListadoAlbumAsync() {
            this.ListadoAlbumAsync(null);
        }
        
        /// <remarks/>
        public void ListadoAlbumAsync(object userState) {
            if ((this.ListadoAlbumOperationCompleted == null)) {
                this.ListadoAlbumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoAlbumOperationCompleted);
            }
            this.InvokeAsync("ListadoAlbum", new object[0], this.ListadoAlbumOperationCompleted, userState);
        }
        
        private void OnListadoAlbumOperationCompleted(object arg) {
            if ((this.ListadoAlbumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoAlbumCompleted(this, new ListadoAlbumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaAlbum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaAlbum(string nombre, int anioCreacion, string generoMusical, int idBanda) {
            this.Invoke("AltaAlbum", new object[] {
                        nombre,
                        anioCreacion,
                        generoMusical,
                        idBanda});
        }
        
        /// <remarks/>
        public void AltaAlbumAsync(string nombre, int anioCreacion, string generoMusical, int idBanda) {
            this.AltaAlbumAsync(nombre, anioCreacion, generoMusical, idBanda, null);
        }
        
        /// <remarks/>
        public void AltaAlbumAsync(string nombre, int anioCreacion, string generoMusical, int idBanda, object userState) {
            if ((this.AltaAlbumOperationCompleted == null)) {
                this.AltaAlbumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaAlbumOperationCompleted);
            }
            this.InvokeAsync("AltaAlbum", new object[] {
                        nombre,
                        anioCreacion,
                        generoMusical,
                        idBanda}, this.AltaAlbumOperationCompleted, userState);
        }
        
        private void OnAltaAlbumOperationCompleted(object arg) {
            if ((this.AltaAlbumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaAlbumCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaAlbum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaAlbum(int idAlbum) {
            this.Invoke("BajaAlbum", new object[] {
                        idAlbum});
        }
        
        /// <remarks/>
        public void BajaAlbumAsync(int idAlbum) {
            this.BajaAlbumAsync(idAlbum, null);
        }
        
        /// <remarks/>
        public void BajaAlbumAsync(int idAlbum, object userState) {
            if ((this.BajaAlbumOperationCompleted == null)) {
                this.BajaAlbumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaAlbumOperationCompleted);
            }
            this.InvokeAsync("BajaAlbum", new object[] {
                        idAlbum}, this.BajaAlbumOperationCompleted, userState);
        }
        
        private void OnBajaAlbumOperationCompleted(object arg) {
            if ((this.BajaAlbumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaAlbumCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarCancionAlbum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarCancionAlbum(int idCancion, int idAlbum) {
            this.Invoke("AgregarCancionAlbum", new object[] {
                        idCancion,
                        idAlbum});
        }
        
        /// <remarks/>
        public void AgregarCancionAlbumAsync(int idCancion, int idAlbum) {
            this.AgregarCancionAlbumAsync(idCancion, idAlbum, null);
        }
        
        /// <remarks/>
        public void AgregarCancionAlbumAsync(int idCancion, int idAlbum, object userState) {
            if ((this.AgregarCancionAlbumOperationCompleted == null)) {
                this.AgregarCancionAlbumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarCancionAlbumOperationCompleted);
            }
            this.InvokeAsync("AgregarCancionAlbum", new object[] {
                        idCancion,
                        idAlbum}, this.AgregarCancionAlbumOperationCompleted, userState);
        }
        
        private void OnAgregarCancionAlbumOperationCompleted(object arg) {
            if ((this.AgregarCancionAlbumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarCancionAlbumCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuitarCancionAlbum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void QuitarCancionAlbum(int idCancion, int idAlbum) {
            this.Invoke("QuitarCancionAlbum", new object[] {
                        idCancion,
                        idAlbum});
        }
        
        /// <remarks/>
        public void QuitarCancionAlbumAsync(int idCancion, int idAlbum) {
            this.QuitarCancionAlbumAsync(idCancion, idAlbum, null);
        }
        
        /// <remarks/>
        public void QuitarCancionAlbumAsync(int idCancion, int idAlbum, object userState) {
            if ((this.QuitarCancionAlbumOperationCompleted == null)) {
                this.QuitarCancionAlbumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuitarCancionAlbumOperationCompleted);
            }
            this.InvokeAsync("QuitarCancionAlbum", new object[] {
                        idCancion,
                        idAlbum}, this.QuitarCancionAlbumOperationCompleted, userState);
        }
        
        private void OnQuitarCancionAlbumOperationCompleted(object arg) {
            if ((this.QuitarCancionAlbumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuitarCancionAlbumCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarBandas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOBanda[] ListarBandas() {
            object[] results = this.Invoke("ListarBandas", new object[0]);
            return ((VOBanda[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarBandasAsync() {
            this.ListarBandasAsync(null);
        }
        
        /// <remarks/>
        public void ListarBandasAsync(object userState) {
            if ((this.ListarBandasOperationCompleted == null)) {
                this.ListarBandasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarBandasOperationCompleted);
            }
            this.InvokeAsync("ListarBandas", new object[0], this.ListarBandasOperationCompleted, userState);
        }
        
        private void OnListarBandasOperationCompleted(object arg) {
            if ((this.ListarBandasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarBandasCompleted(this, new ListarBandasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaBanda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaBanda(string nombre, string generoMusical, int anioC, int anioS) {
            this.Invoke("AltaBanda", new object[] {
                        nombre,
                        generoMusical,
                        anioC,
                        anioS});
        }
        
        /// <remarks/>
        public void AltaBandaAsync(string nombre, string generoMusical, int anioC, int anioS) {
            this.AltaBandaAsync(nombre, generoMusical, anioC, anioS, null);
        }
        
        /// <remarks/>
        public void AltaBandaAsync(string nombre, string generoMusical, int anioC, int anioS, object userState) {
            if ((this.AltaBandaOperationCompleted == null)) {
                this.AltaBandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaBandaOperationCompleted);
            }
            this.InvokeAsync("AltaBanda", new object[] {
                        nombre,
                        generoMusical,
                        anioC,
                        anioS}, this.AltaBandaOperationCompleted, userState);
        }
        
        private void OnAltaBandaOperationCompleted(object arg) {
            if ((this.AltaBandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaBandaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaBanda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaBanda(int idBanda) {
            this.Invoke("BajaBanda", new object[] {
                        idBanda});
        }
        
        /// <remarks/>
        public void BajaBandaAsync(int idBanda) {
            this.BajaBandaAsync(idBanda, null);
        }
        
        /// <remarks/>
        public void BajaBandaAsync(int idBanda, object userState) {
            if ((this.BajaBandaOperationCompleted == null)) {
                this.BajaBandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaBandaOperationCompleted);
            }
            this.InvokeAsync("BajaBanda", new object[] {
                        idBanda}, this.BajaBandaOperationCompleted, userState);
        }
        
        private void OnBajaBandaOperationCompleted(object arg) {
            if ((this.BajaBandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaBandaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarIntegranteBanda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AgregarIntegranteBanda(int idIntegrante, int idBanda) {
            this.Invoke("AgregarIntegranteBanda", new object[] {
                        idIntegrante,
                        idBanda});
        }
        
        /// <remarks/>
        public void AgregarIntegranteBandaAsync(int idIntegrante, int idBanda) {
            this.AgregarIntegranteBandaAsync(idIntegrante, idBanda, null);
        }
        
        /// <remarks/>
        public void AgregarIntegranteBandaAsync(int idIntegrante, int idBanda, object userState) {
            if ((this.AgregarIntegranteBandaOperationCompleted == null)) {
                this.AgregarIntegranteBandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarIntegranteBandaOperationCompleted);
            }
            this.InvokeAsync("AgregarIntegranteBanda", new object[] {
                        idIntegrante,
                        idBanda}, this.AgregarIntegranteBandaOperationCompleted, userState);
        }
        
        private void OnAgregarIntegranteBandaOperationCompleted(object arg) {
            if ((this.AgregarIntegranteBandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarIntegranteBandaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QuitarIntegranteBanda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void QuitarIntegranteBanda(int idIntegrante, int idBanda) {
            this.Invoke("QuitarIntegranteBanda", new object[] {
                        idIntegrante,
                        idBanda});
        }
        
        /// <remarks/>
        public void QuitarIntegranteBandaAsync(int idIntegrante, int idBanda) {
            this.QuitarIntegranteBandaAsync(idIntegrante, idBanda, null);
        }
        
        /// <remarks/>
        public void QuitarIntegranteBandaAsync(int idIntegrante, int idBanda, object userState) {
            if ((this.QuitarIntegranteBandaOperationCompleted == null)) {
                this.QuitarIntegranteBandaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuitarIntegranteBandaOperationCompleted);
            }
            this.InvokeAsync("QuitarIntegranteBanda", new object[] {
                        idIntegrante,
                        idBanda}, this.QuitarIntegranteBandaOperationCompleted, userState);
        }
        
        private void OnQuitarIntegranteBandaOperationCompleted(object arg) {
            if ((this.QuitarIntegranteBandaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuitarIntegranteBandaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCanciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOCancion[] ListarCanciones() {
            object[] results = this.Invoke("ListarCanciones", new object[0]);
            return ((VOCancion[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCancionesAsync() {
            this.ListarCancionesAsync(null);
        }
        
        /// <remarks/>
        public void ListarCancionesAsync(object userState) {
            if ((this.ListarCancionesOperationCompleted == null)) {
                this.ListarCancionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCancionesOperationCompleted);
            }
            this.InvokeAsync("ListarCanciones", new object[0], this.ListarCancionesOperationCompleted, userState);
        }
        
        private void OnListarCancionesOperationCompleted(object arg) {
            if ((this.ListarCancionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCancionesCompleted(this, new ListarCancionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaCancion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaCancion(string nombre, int duracion, string genero, int cantante, int anio) {
            this.Invoke("AltaCancion", new object[] {
                        nombre,
                        duracion,
                        genero,
                        cantante,
                        anio});
        }
        
        /// <remarks/>
        public void AltaCancionAsync(string nombre, int duracion, string genero, int cantante, int anio) {
            this.AltaCancionAsync(nombre, duracion, genero, cantante, anio, null);
        }
        
        /// <remarks/>
        public void AltaCancionAsync(string nombre, int duracion, string genero, int cantante, int anio, object userState) {
            if ((this.AltaCancionOperationCompleted == null)) {
                this.AltaCancionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaCancionOperationCompleted);
            }
            this.InvokeAsync("AltaCancion", new object[] {
                        nombre,
                        duracion,
                        genero,
                        cantante,
                        anio}, this.AltaCancionOperationCompleted, userState);
        }
        
        private void OnAltaCancionOperationCompleted(object arg) {
            if ((this.AltaCancionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaCancionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaCancion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaCancion(int idCancion) {
            this.Invoke("BajaCancion", new object[] {
                        idCancion});
        }
        
        /// <remarks/>
        public void BajaCancionAsync(int idCancion) {
            this.BajaCancionAsync(idCancion, null);
        }
        
        /// <remarks/>
        public void BajaCancionAsync(int idCancion, object userState) {
            if ((this.BajaCancionOperationCompleted == null)) {
                this.BajaCancionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaCancionOperationCompleted);
            }
            this.InvokeAsync("BajaCancion", new object[] {
                        idCancion}, this.BajaCancionOperationCompleted, userState);
        }
        
        private void OnBajaCancionOperationCompleted(object arg) {
            if ((this.BajaCancionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaCancionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarIntegrante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VOIntegrante[] ListarIntegrante() {
            object[] results = this.Invoke("ListarIntegrante", new object[0]);
            return ((VOIntegrante[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarIntegranteAsync() {
            this.ListarIntegranteAsync(null);
        }
        
        /// <remarks/>
        public void ListarIntegranteAsync(object userState) {
            if ((this.ListarIntegranteOperationCompleted == null)) {
                this.ListarIntegranteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarIntegranteOperationCompleted);
            }
            this.InvokeAsync("ListarIntegrante", new object[0], this.ListarIntegranteOperationCompleted, userState);
        }
        
        private void OnListarIntegranteOperationCompleted(object arg) {
            if ((this.ListarIntegranteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarIntegranteCompleted(this, new ListarIntegranteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaIntegrante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaIntegrante(string nombre, string apellido, System.DateTime fechaNacimiento) {
            this.Invoke("AltaIntegrante", new object[] {
                        nombre,
                        apellido,
                        fechaNacimiento});
        }
        
        /// <remarks/>
        public void AltaIntegranteAsync(string nombre, string apellido, System.DateTime fechaNacimiento) {
            this.AltaIntegranteAsync(nombre, apellido, fechaNacimiento, null);
        }
        
        /// <remarks/>
        public void AltaIntegranteAsync(string nombre, string apellido, System.DateTime fechaNacimiento, object userState) {
            if ((this.AltaIntegranteOperationCompleted == null)) {
                this.AltaIntegranteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaIntegranteOperationCompleted);
            }
            this.InvokeAsync("AltaIntegrante", new object[] {
                        nombre,
                        apellido,
                        fechaNacimiento}, this.AltaIntegranteOperationCompleted, userState);
        }
        
        private void OnAltaIntegranteOperationCompleted(object arg) {
            if ((this.AltaIntegranteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaIntegranteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaIntegrante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaIntegrante(int idIntegrante) {
            this.Invoke("BajaIntegrante", new object[] {
                        idIntegrante});
        }
        
        /// <remarks/>
        public void BajaIntegranteAsync(int idIntegrante) {
            this.BajaIntegranteAsync(idIntegrante, null);
        }
        
        /// <remarks/>
        public void BajaIntegranteAsync(int idIntegrante, object userState) {
            if ((this.BajaIntegranteOperationCompleted == null)) {
                this.BajaIntegranteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaIntegranteOperationCompleted);
            }
            this.InvokeAsync("BajaIntegrante", new object[] {
                        idIntegrante}, this.BajaIntegranteOperationCompleted, userState);
        }
        
        private void OnBajaIntegranteOperationCompleted(object arg) {
            if ((this.BajaIntegranteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaIntegranteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOAlbum {
        
        private int idField;
        
        private string nombreField;
        
        private int anioCreacionField;
        
        private int idBandaField;
        
        private string generoMusicalField;
        
        private VOCancion[] cancionesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int AnioCreacion {
            get {
                return this.anioCreacionField;
            }
            set {
                this.anioCreacionField = value;
            }
        }
        
        /// <remarks/>
        public int IdBanda {
            get {
                return this.idBandaField;
            }
            set {
                this.idBandaField = value;
            }
        }
        
        /// <remarks/>
        public string GeneroMusical {
            get {
                return this.generoMusicalField;
            }
            set {
                this.generoMusicalField = value;
            }
        }
        
        /// <remarks/>
        public VOCancion[] Canciones {
            get {
                return this.cancionesField;
            }
            set {
                this.cancionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOCancion {
        
        private int idField;
        
        private string nombreField;
        
        private int anioField;
        
        private string generoMusicalField;
        
        private int duracionField;
        
        private int idCantanteField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int Anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
            }
        }
        
        /// <remarks/>
        public string GeneroMusical {
            get {
                return this.generoMusicalField;
            }
            set {
                this.generoMusicalField = value;
            }
        }
        
        /// <remarks/>
        public int Duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
            }
        }
        
        /// <remarks/>
        public int IdCantante {
            get {
                return this.idCantanteField;
            }
            set {
                this.idCantanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOIntegrante {
        
        private int idField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private System.DateTime fechaNacimientoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VOBanda {
        
        private int idField;
        
        private string nombreField;
        
        private int anioCreacionField;
        
        private string generoMusicalField;
        
        private VOCancion[] integrantesField;
        
        private int anioSeparacionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int AnioCreacion {
            get {
                return this.anioCreacionField;
            }
            set {
                this.anioCreacionField = value;
            }
        }
        
        /// <remarks/>
        public string GeneroMusical {
            get {
                return this.generoMusicalField;
            }
            set {
                this.generoMusicalField = value;
            }
        }
        
        /// <remarks/>
        public VOCancion[] Integrantes {
            get {
                return this.integrantesField;
            }
            set {
                this.integrantesField = value;
            }
        }
        
        /// <remarks/>
        public int AnioSeparacion {
            get {
                return this.anioSeparacionField;
            }
            set {
                this.anioSeparacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListadoAlbumCompletedEventHandler(object sender, ListadoAlbumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoAlbumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoAlbumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOAlbum[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOAlbum[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AltaAlbumCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void BajaAlbumCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AgregarCancionAlbumCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void QuitarCancionAlbumCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarBandasCompletedEventHandler(object sender, ListarBandasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarBandasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarBandasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOBanda[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOBanda[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AltaBandaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void BajaBandaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AgregarIntegranteBandaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void QuitarIntegranteBandaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarCancionesCompletedEventHandler(object sender, ListarCancionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCancionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCancionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOCancion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOCancion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AltaCancionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void BajaCancionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ListarIntegranteCompletedEventHandler(object sender, ListarIntegranteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarIntegranteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarIntegranteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VOIntegrante[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VOIntegrante[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AltaIntegranteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void BajaIntegranteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591